[build]
builder = "nixpacks"
base_image = "python:3.11"

[phases.backend]
name = "Backend"
cmds = [
    "echo '--- Backend Phase: Starting ---'",
    "ls -la /usr/local/bin",  # Liste le contenu de /usr/local/bin pour voir où sont python et pip
    "/usr/local/bin/python --version",  # Vérifiez la version de Python explicitement
    "/usr/local/bin/python -m pip --version",  # Vérifiez la version de pip via le module Python explicitement
    "ls -l /app",  # Liste les fichiers dans le répertoire de travail pour vérifier la présence de requirements.txt
    "/usr/local/bin/python -m pip install --upgrade pip",  # Mise à jour de pip pour s'assurer d'avoir la dernière version
    "/usr/local/bin/python -m pip install -r back_socratic/requirements.txt",
    "echo '--- Backend Phase: Installed Python dependencies ---'",
    "/usr/local/bin/python back_socratic/airs/server_run.py",
    "echo '--- Backend Phase: Completed ---'"
]

[phases.frontend]
name = "Frontend"
cmds = [
    "echo '--- Frontend Phase: Starting ---'",
    "cd web/test_app_modulaire_socratic",
    "yarn install",
    "echo '--- Frontend Phase: Installed frontend dependencies ---'",
    "echo '--- Frontend Phase: Completed ---'"
]

[deploy]
[[deploy.services]]
name = "backend"
phases = ["backend"]
env = { PORT = "8000" }

[[deploy.services]]
name = "frontend-upenn"
phases = ["frontend"]
cmds = [
    "echo '--- Starting frontend-upenn ---'",
    "cd web/test_app_modulaire_socratic",
    "yarn start:upenn"
]
env = { PORT = "3001" }

[[deploy.services]]
name = "frontend-harvard"
phases = ["frontend"]
cmds = [
    "echo '--- Starting frontend-harvard ---'",
    "cd web/test_app_modulaire_socratic",
    "yarn start:harvard"
]
env = { PORT = "3002" }

[[deploy.services]]
name = "frontend-usyd"
phases = ["frontend"]
cmds = [
    "echo '--- Starting frontend-usyd ---'",
    "cd web/test_app_modulaire_socratic",
    "yarn start:usyd"
]
env = { PORT = "3003" }
