[build]
builder = "nixpacks"
base_image = "python:3.11-slim"

[phases.setup]
name = "Setup"
cmds = [
    "echo '--- Setup Phase: Starting ---'",
    "apt-get update",
    "apt-get install -y curl gnupg",
    "curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -",
    "echo 'deb https://dl.yarnpkg.com/debian/ stable main' | tee /etc/apt/sources.list.d/yarn.list",
    "apt-get update && apt-get install -y yarn",
    "apt-get install -y python3 python3-pip",  # Installation manuelle de Python3 et pip si nécessaire
    "ln -s /usr/bin/python3 /usr/bin/python",  # Crée un lien symbolique pour python vers python3
    "echo '--- Setup Phase: Completed ---'"
]

[phases.backend]
name = "Backend"
cmds = [
    "echo '--- Backend Phase: Starting ---'",
    "python3 --version",  # Vérifiez la version de Python3 explicitement
    "python3 -m pip --version",  # Vérifiez la version de pip via le module Python3 explicitement
    "ls -l /app",
    "python3 -m pip install --upgrade pip",
    "python3 -m pip install -r back_socratic/requirements.txt",
    "echo '--- Backend Phase: Installed Python dependencies ---'",
    "python3 back_socratic/airs/server_run.py",
    "echo '--- Backend Phase: Completed ---'"
]

[phases.frontend]
name = "Frontend"
cmds = [
    "echo '--- Frontend Phase: Starting ---'",
    "cd web/test_app_modulaire_socratic",
    "yarn install",
    "echo '--- Frontend Phase: Installed frontend dependencies ---'",
    "echo '--- Frontend Phase: Completed ---'"
]

[deploy]
[[deploy.services]]
name = "backend"
phases = ["setup", "backend"]
env = { PORT = "8000" }

[[deploy.services]]
name = "frontend-upenn"
phases = ["frontend"]
cmds = [
    "echo '--- Starting frontend-upenn ---'",
    "cd web/test_app_modulaire_socratic",
    "yarn start:upenn"
]
env = { PORT = "3001" }

[[deploy.services]]
name = "frontend-harvard"
phases = ["frontend"]
cmds = [
    "echo '--- Starting frontend-harvard ---'",
    "cd web/test_app_modulaire_socratic",
    "yarn start:harvard"
]
env = { PORT = "3002" }

[[deploy.services]]
name = "frontend-usyd"
phases = ["frontend"]
cmds = [
    "echo '--- Starting frontend-usyd ---'",
    "cd web/test_app_modulaire_socratic",
    "yarn start:usyd"
]
env = { PORT = "3003" }
