[build]
builder = "nixpacks"

[phases]

[phases.setup]
name = "Setup"
cmds = [
    "apt-get update && apt-get install -y python3-pip"
]

[phases.backend]
name = "Backend"
cmds = [
    "pip install -r backend/back_socratic/requirements.txt",
    "python backend/back_socratic/airs/server_run.py"
]

[phases.frontend]
name = "Frontend"
cmds = [
    "cd web/test_app_modulaire_socratic",
    "yarn install"
]

[deploy]
[[deploy.services]]
name = "backend"
phases = ["setup", "backend"]
env = { PORT = "8000" }

[[deploy.services]]
name = "frontend-upenn"
phases = ["frontend"]
cmds = ["cd web/test_app_modulaire_socratic", "yarn start:upenn"]
env = { PORT = "3001" }

[[deploy.services]]
name = "frontend-harvard"
phases = ["frontend"]
cmds = ["cd web/test_app_modulaire_socratic", "yarn start:harvard"]
env = { PORT = "3002" }

[[deploy.services]]
name = "frontend-usyd"
phases = ["frontend"]
cmds = ["cd web/test_app_modulaire_socratic", "yarn start:usyd"]
env = { PORT = "3003" }
