[build]
builder = "nixpacks"
base_image = "python:3.11"

[phases.backend]
name = "Backend"
cmds = [
    "echo '--- Backend Phase: Starting ---'",
    "ls -la /usr/local/bin",  # Liste le contenu de /usr/local/bin pour voir où sont python et pip
    "ls -la /usr/bin",  # Liste le contenu de /usr/bin pour vérifier d'autres emplacements possibles
    "ls -la /bin",  # Liste le contenu de /bin pour vérifier d'autres emplacements possibles
    "ls -la /usr/local",  # Liste le contenu de /usr/local pour vérifier d'autres emplacements possibles
    "find / -name python",  # Cherche le binaire python sur tout le système
    "echo '--- Searching for Python and pip completed ---'",
    "python --version || true",  # Vérifie la version de Python, continue même si erreur
    "python3 --version || true",  # Vérifie la version de Python3, continue même si erreur
    "pip --version || true",  # Vérifie la version de pip, continue même si erreur
    "pip3 --version || true",  # Vérifie la version de pip3, continue même si erreur
    "echo '--- Backend Phase diagnostics completed ---'"
]

[phases.frontend]
name = "Frontend"
cmds = [
    "echo '--- Frontend Phase: Starting ---'",
    "cd web/test_app_modulaire_socratic",
    "yarn install",
    "echo '--- Frontend Phase: Installed frontend dependencies ---'",
    "echo '--- Frontend Phase: Completed ---'"
]

[deploy]
[[deploy.services]]
name = "backend"
phases = ["backend"]
env = { PORT = "8000" }

[[deploy.services]]
name = "frontend-upenn"
phases = ["frontend"]
cmds = [
    "echo '--- Starting frontend-upenn ---'",
    "cd web/test_app_modulaire_socratic",
    "yarn start:upenn"
]
env = { PORT = "3001" }

[[deploy.services]]
name = "frontend-harvard"
phases = ["frontend"]
cmds = [
    "echo '--- Starting frontend-harvard ---'",
    "cd web/test_app_modulaire_socratic",
    "yarn start:harvard"
]
env = { PORT = "3002" }

[[deploy.services]]
name = "frontend-usyd"
phases = ["frontend"]
cmds = [
    "echo '--- Starting frontend-usyd ---'",
    "cd web/test_app_modulaire_socratic",
    "yarn start:usyd"
]
env = { PORT = "3003" }
